import { Footer, NavBar } from "@/components";
import { Metadata } from "next";


interface MetadataProps {
  slug: string;
}

export const generateMetadata = ({ slug }: MetadataProps) => {
  const metadata: Metadata = {
    title: "Audiophile",
    description: "Generated by create next app",
    keywords: "audiophile, ecommerce, headphones, speakers, earphones",
  };

  return metadata;
};

interface ProductLayoutProps {
  children: React.ReactNode;
}

export default function ProductLayOuyt({ children }: ProductLayoutProps) {
  return (
    <main>
        <header className="bg-black w-full py-10 border-smoke_white sticky text-white items-center">
            <NavBar/>
        </header>
        { children }
        <footer>
            <Footer />
        </footer>
    </main>
  );
}
