import { Footer, NavBar } from "@/components";
import { Metadata } from "next";

type Props = {
  params: { slug: string };
};

export const generateMetadata = ({ params }: Props) => {
  const metadata: Metadata = {
    title: "Audiophile",
    description: "Generated by create next app",
    keywords: "audiophile, ecommerce, headphones, speakers, earphones",
  };

  return metadata;
};

interface ProductLayoutProps {
  children: React.ReactNode;
}

export default function ProductLayOuyt({ children }: ProductLayoutProps) {
  return (
    <main className="w-full h-screen">
      <header className="bg-black w-full py-10 border-smoke_white sticky text-white items-center">
        <NavBar />
      </header>
      {children}
      <footer>
        <Footer />
      </footer>
    </main>
  );
}
