import { Footer, NavBar } from "@/components";



export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
  keywords: "audiophile, ecommerce, headphones, speakers, earphones",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <header className="bg-black w-full py-10 border-smoke_white sticky text-white items-center">
        <NavBar divider />
      </header>
      {children}
      <footer>
        <Footer />
      </footer>
    </section>
  );
}
